### ISSUE TITLE
Problem to access owncloud selfsigned (E4.5)

### ISSUE THREAD

**Issue by j2g2rp** [ubports/webbrowser-component#2]
Hi.
I'm having a problem to access to my ownclod (selfsigned encrypt).
First the webbrowser notices me that it could be risky to access to the page (that isn't a problem really but i don't know if it could be related)
Once that i overrides it, I'm redirected to login page. But there i can't login in to my cloud, looks like the buttons enter of keyboard or arroy from page to login doesn't work at all.
If I'm correct I hadn't this problem in OTA15 from canonical. Now I'm on r8.

**Comment by ernesst** [comment]
A way to solve out is to use Let's encrypt to sign your server. 

It might me because the certificate is selfsigned and not installed in your phone.

**Comment by NeoTheThird** [comment]
This issue was moved to ubports/webbrowser-app#6
