### ISSUE TITLE
Download fails on already authenticated site

### ISSUE THREAD

**Issue by ernesst** [ubports/webbrowser-component#3]
Reopening the bug here : 

https://bugs.launchpad.net/ubuntu/+source/webbrowser-app/+bug/1581892
https://bugs.launchpad.net/ubuntu/+source/webbrowser-app/+bug/1548020

Some discussion https://lists.launchpad.net/ubuntu-phone/msg22840.html

**Comment by NeoTheThird** [comment]
This issue was moved to ubports/webbrowser-app#5
